# Generated by Django 4.1.1 on 2022-09-08 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_creditofficer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditOfficer',
        ),
    ]
