# Generated by Django 4.1.1 on 2022-09-09 08:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest',
        ),
        migrations.AlterField(
            model_name='loan',
            name='payable_amount',
            field=models.FloatField(default=0, validators=[app.models.calculate_interest]),
        ),
    ]
