# Generated by Django 4.1.1 on 2022-09-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_loan_interest_alter_loan_payable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.FloatField(default=0),
        ),
    ]
