# Generated by Django 4.1.1 on 2022-09-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_loan_interest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='user',
            new_name='creditofficer_id',
        ),
    ]
