# Generated by Django 4.1.1 on 2022-09-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_user_loan_creditofficer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
