# Generated by Django 4.1.1 on 2022-09-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_loan_customer_id_customerapply_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
    ]
