# Generated by Django 4.1.1 on 2022-09-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_loan_creditofficer_remove_loan_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
