# Generated by Django 4.1.1 on 2022-09-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('interest_rate', models.FloatField(default=0)),
                ('num_times_interest', models.FloatField(default=0)),
                ('time_period', models.FloatField(default=0)),
                ('time_periods', models.FloatField(default=0)),
                ('compound_interest', models.FloatField(default=0)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('creditofficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.creditofficer')),
            ],
        ),
    ]
