# Generated by Django 4.1.1 on 2022-09-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='time_periods',
            field=models.CharField(default=0, max_length=12),
        ),
    ]
