# Generated by Django 4.1.1 on 2022-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_loan_time_periods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='compound_interest',
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='num_times_interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='time_period',
            field=models.IntegerField(default=0),
        ),
    ]
