# Generated by Django 4.1.1 on 2022-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_loan_amount_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='num_times_interest',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
