# Generated by Django 4.1.1 on 2022-09-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_loan_amount_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
